server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/interview_simulator?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
jwt:
  secret: interviewSecretKey
  expiration: 86400000 # 1天

# 视频存储配置
video:
  storage:
    path: F:/interview-videos
    max-size: 1GB
  access-url-prefix: /videos/

python:
  interpreter: D:/anaconda3/envs/interview/python.exe
  base_script_path: F:/multimodal-interview/backend/src/main/python

logging:
  charset:
    console: UTF-8
  level:
    root: INFO
    org:
      hibernate:
        SQL: OFF
        type:
          descriptor:
            sql:
              BasicBinder: OFF
    com:
      example:
        interview:
          service:
            AiResponseService: WARN
            BigModelService: WARN
            LargeModelService: WARN
          controller:
            InterviewAnalysisController: WARN 

# 讯飞虚拟人avatar服务配置
avatar:
  app_id: 4478a044
  api_key: 8a2bac2e4450c1eaf5f27c0835f2cf19
  api_secret: OTg0ODEwMGMzZTI4NGQ2NjEwNWMxMDlk
  avatar_id: cnrfb86h2000000004 # 你的avatarId，需在讯飞平台获取
  vcn: x4_yezi # 你的vcn，需在讯飞平台获取
  scene_id: 205693782128201728