server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/interview_simulator?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
jwt:
  secret: interviewSecretKey
  expiration: 86400000 # 1天

# 视频存储配置
video:
  storage:
    path: F:/interview-videos
    max-size: 100MB 