server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/interview_simulator?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
jwt:
  secret: interviewSecretKey
  expiration: 86400000 # 1天

# 视频存储配置
video:
  storage:
    path: F:/interview-videos
    max-size: 1GB
  access-url-prefix: /videos/

python:
  interpreter: D:/miniconda3/envs/interview/python.exe
  script_path: F:/multimodal-interview/backend/src/main/python

logging:
  charset:
    console: UTF-8
  level:
    org:
      hibernate:
        SQL: off
        type:
          descriptor:
            sql:
              BasicBinder: off 

# 讯飞虚拟人avatar服务配置
avatar:
  app_id: 528394f2
  api_key: 0dccac0467edaaeb86ca3f0fc0bead37
  api_secret: NWU3MWE4YTM1YmRiYjQxMDgxN2E1MTQ3
  avatar_id: cnrfb86h2000000004 # 你的avatarId，需在讯飞平台获取
  vcn: x4_yezi # 你的vcn，需在讯飞平台获取
  scene_id: 201309244992131072